No sshtunnel module
KeckObservatory/RemoteObserving pull request #22
Opened 2020-03-16 21:36 UTC by klanclos

Removes dependency on the sshtunnel module.

2020-03-16 22:56 UTC, joshjriley approved these changes
Tested and changes look good to me.

2020-03-16 23:18 UTC, joshwalawender commented
I'd like a bit of a discussion of the pros and cons of removing this.  Having the dependency makes installation harder yes, but in general having calls to the shell to run things strikes me as more fragile.  I've always had the goal in code of not depending on the shell unless absolutely necessary because it is not under our control.  At least with the `sshtunnel` package it is under our control in that we work in the KRO conda environment, so there should be no unexpected upgrade or changes in API (we can fix the version).  When calling out to the shell, that's not under our control.

2020-03-16 23:50 UTC, klanclos commented
Having to carry around an import that's not part of the standard install is going to be more fragile. The ssh command line options have been in-place for more than a decade, probably more like two decades; they aren't going to change under our feet without a lot of advance warning. And if they did, the sshtunnel module would probably stop working too!

2020-03-17 23:13 UTC, joshwalawender commented on keck_vnc_launcher.py
> +        if ssh_pkey is not None:
Can you add comment to explain this block of code?

2020-03-17 23:14 UTC, joshwalawender commented on keck_vnc_launcher.py
> +        if process.poll() is not None:
Comment here too

2020-03-17 23:14 UTC, joshwalawender commented on keck_vnc_launcher.py
> +        checks = 50
Comment here as well please

2020-03-17 23:15 UTC, joshwalawender requested changes
Looks good as per our discussion earlier.  Would be good to get some explanatory comments in for future reference.

2020-03-18 03:31 UTC, klanclos commented
I couldn't figure out how to successfully check out the branch on another machine, so I had to go back to my original checkout to make changes. I added several comments to the open_ssh_tunnel() routine.

2020-03-18 05:55 UTC, joshwalawender approved these changes

2020-03-18 05:56 UTC, merged